export type Alignment = 'GOOD' | 'EVIL'

export interface Role {
  alignment: Alignment
  id: string
  displayName: string
  description: string
  image: string
  information: number // Amount of information the role provides during the game
  correction: number // Amount of correction the role provides during the game
  balance: number // Positive for good, negative for evil
  shootable: boolean // Has information or mechanics during the game to narrow the Blind Hunter's shot
  minPlayers: number // Minimum players required to include this role
  maxPlayers: number // Maximum players allowed to include this role
}

export const Roles: Record<string, Role> = {
  Cleric: {
    id: 'Cleric',
    displayName: 'Cleric',
    image: '📿',
    minPlayers: 0,
    maxPlayers: 100,
    balance: 3,
    information: 1,
    correction: 0,
    shootable: true,
    alignment: 'GOOD',
    description: 'Knows loyalty of first leader.',
  },
  'Loyal Servant': {
    id: 'Loyal Servant',
    displayName: 'Loyal Servant',
    image: '⚔️',
    minPlayers: 0,
    maxPlayers: 100,
    information: 0,
    correction: 0,
    balance: 1,
    shootable: false,
    alignment: 'GOOD',
    description: 'No special abilities.',
  },
  'Loyal Servant B': {
    id: 'Loyal Servant B',
    displayName: 'Loyal Servant',
    image: '⚔️',
    minPlayers: 0,
    maxPlayers: 100,
    information: 0,
    correction: 0,
    balance: 1,
    shootable: false,
    alignment: 'GOOD',
    description: 'No special abilities.',
  },
  'Loyal Servant C': {
    id: 'Loyal Servant C',
    displayName: 'Loyal Servant',
    image: '⚔️',
    minPlayers: 0,
    maxPlayers: 100,
    information: 0,
    correction: 0,
    balance: 1,
    shootable: false,
    alignment: 'GOOD',
    description: 'No special abilities.',
  },
  Arthur: {
    id: 'Arthur',
    displayName: 'Arthur',
    image: '👑',
    minPlayers: 0,
    maxPlayers: 100,
    balance: 3,
    information: 1,
    correction: 0,
    shootable: true,
    alignment: 'GOOD',
    description: 'Knows Morgan le Fay.',
  },
  Archduke: {
    id: 'Archduke',
    displayName: 'Archduke',
    image: '🙌',
    minPlayers: 8,
    maxPlayers: 100,
    balance: 3,
    information: 0,
    correction: 2,
    shootable: false,
    alignment: 'GOOD',
    description: "Can move one ally's hand during Good's Last Stand.",
  },
  Duke: {
    id: 'Duke',
    displayName: 'Duke',
    image: '👏',
    minPlayers: 6,
    maxPlayers: 100,
    balance: 2,
    information: 0,
    correction: 1,
    shootable: false,
    alignment: 'GOOD',
    description: "Can drop one ally's hand during Good's Last Stand.",
  },
  Apprentice: {
    id: 'Apprentice',
    displayName: 'Apprentice',
    image: '👐',
    minPlayers: 6,
    maxPlayers: 100,
    balance: 2,
    information: 0,
    correction: 1,
    shootable: false,
    alignment: 'GOOD',
    description: "Can delay own second hand during Good's Last Stand.",
  },
  Troublemaker: {
    id: 'Troublemaker',
    displayName: 'Troublemaker',
    image: '😨',
    minPlayers: 6,
    maxPlayers: 100,
    balance: -2,
    information: 0,
    correction: 0,
    shootable: true,
    alignment: 'GOOD',
    description: 'Must give red card during loyalty check.',
  },
  Youth: {
    id: 'Youth',
    displayName: 'Youth',
    image: '👦',
    minPlayers: 0,
    maxPlayers: 100,
    balance: -3,
    information: 0,
    correction: 0,
    shootable: true,
    alignment: 'GOOD',
    description: 'Must fail quest if flamed.',
  },
  'Arthur/Cleric': {
    id: 'Arthur/Cleric',
    displayName: 'Arthur/Cleric',
    image: '⛪️',
    minPlayers: 0,
    maxPlayers: 100,
    balance: 3,
    information: 1,
    correction: 0,
    shootable: true,
    alignment: 'GOOD',
    description:
      'Randomly pick Arthur or Cleric and tuck the other role away in secret.',
  },
  'Troubled Youth': {
    id: 'Troubled Youth',
    displayName: 'Troubled Youth',
    image: '😱',
    minPlayers: 0,
    maxPlayers: 100,
    balance: -1,
    information: 0,
    correction: 0,
    shootable: true,
    alignment: 'GOOD',
    description:
      'Randomly pick Troublemaker or Youth and tuck the other role away in secret.',
  },
  'RNG Good': {
    id: 'RNG Good',
    displayName: 'RNG Good',
    image: '🧑‍🧑‍🧒',
    minPlayers: 4,
    maxPlayers: 5,
    balance: 2,
    information: 1,
    correction: 0,
    shootable: true,
    alignment: 'GOOD',
    description:
      '4-5P Only. Randomly pick 2 among Youth, Loyal Servant, or Cleric.',
  },
  'RNG Good B': {
    id: 'RNG Good B',
    displayName: 'RNG Good',
    image: '🧑‍🧑‍🧒',
    minPlayers: 4,
    maxPlayers: 5,
    balance: 2,
    information: 1,
    correction: 0,
    shootable: true,
    alignment: 'GOOD',
    description:
      '4-5P Only. Randomly pick 2 among Youth, Loyal Servant, or Cleric.',
  },
  'Morgan le Fay': {
    id: 'Morgan le Fay',
    displayName: 'Morgan le Fay',
    image: '❤️‍🔥',
    minPlayers: 0,
    maxPlayers: 100,
    shootable: false,
    balance: -3,
    information: 3,
    correction: 0,
    alignment: 'EVIL',
    description: 'May fail a quest, even when flamed.',
  },
  'Blind Hunter': {
    id: 'Blind Hunter',
    displayName: 'Blind Hunter',
    image: '🏹',
    minPlayers: 0,
    maxPlayers: 100,
    shootable: false,
    balance: 0,
    information: 0,
    correction: 0,
    alignment: 'EVIL',
    description:
      'Does not know evil. Can shoot Cleric plus another role, or just Arthur in the post-game.',
  },
  Minion: {
    id: 'Minion',
    displayName: 'Minion',
    image: '😈',
    minPlayers: 0,
    maxPlayers: 100,
    shootable: false,
    balance: -1,
    information: 1,
    correction: 0,
    alignment: 'EVIL',
    description: 'No special abilities.',
  },
  'Minion B': {
    id: 'Minion B',
    displayName: 'Minion',
    image: '😈',
    minPlayers: 7,
    maxPlayers: 100,
    shootable: false,
    balance: -1,
    information: 1,
    correction: 0,
    alignment: 'EVIL',
    description: 'No special abilities.',
  },
  'Minion C': {
    id: 'Minion C',
    displayName: 'Minion',
    image: '😈',
    minPlayers: 9,
    maxPlayers: 100,
    shootable: false,
    balance: -1,
    information: 1,
    correction: 0,
    alignment: 'EVIL',
    description: 'No special abilities.',
  },
  Trickster: {
    id: 'Trickster',
    displayName: 'Trickster',
    image: '🤥',
    minPlayers: 0,
    maxPlayers: 100,
    shootable: false,
    balance: -4,
    information: 1,
    correction: 0,
    alignment: 'EVIL',
    description:
      'May lie when checked for loyalty or as first leader during pre-game.',
  },
  Revealer: {
    id: 'Revealer',
    displayName: 'Revealer',
    image: '🫣',
    minPlayers: 6,
    maxPlayers: 100,
    shootable: false,
    balance: 1,
    information: 1,
    correction: 0,
    alignment: 'EVIL',
    description: 'Reveals self at the end of the third failing quest.',
  },
  Scion: {
    id: 'Scion',
    displayName: 'Scion',
    image: '🙈',
    minPlayers: 6,
    maxPlayers: 100,
    shootable: false,
    balance: 1,
    information: 0,
    correction: 0,
    alignment: 'EVIL',
    description: 'Does not know evil. Is known by Morgan le Fay.',
  },
  Lunatic: {
    id: 'Lunatic',
    displayName: 'Lunatic',
    image: '🤪',
    minPlayers: 6,
    maxPlayers: 100,
    shootable: false,
    balance: 1,
    information: 1,
    correction: 0,
    alignment: 'EVIL',
    description: 'Must fail every quest when not flamed.',
  },
  Brute: {
    id: 'Brute',
    displayName: 'Brute',
    image: '💪',
    minPlayers: 6,
    maxPlayers: 100,
    shootable: false,
    balance: 1,
    information: 1,
    correction: 0,
    alignment: 'EVIL',
    description: 'Cannot fail Quest 4 or 5.',
  },
  Changeling: {
    id: 'Changeling',
    displayName: 'Changeling',
    image: '😶‍🌫️',
    minPlayers: 6,
    maxPlayers: 100,
    shootable: false,
    balance: 2,
    information: 0,
    correction: 0,
    alignment: 'EVIL',
    description: 'Does not know evil. Evil does not know them.',
  },
  Mutineer: {
    id: 'Mutineer',
    displayName: 'Mutineer',
    image: '🎭',
    minPlayers: 0,
    maxPlayers: 100,
    shootable: false,
    balance: 0,
    information: 0,
    correction: 0,
    alignment: 'EVIL',
    description: "We don't talk about the Mutineer.",
  },
  UNKNOWN: {
    id: 'UNKNOWN',
    displayName: 'INVALID ROLE',
    image: '❌',
    minPlayers: 0,
    maxPlayers: 0,
    balance: -100,
    information: -1,
    correction: -1,
    shootable: false,
    alignment: 'EVIL',
    description: `Could not determine the role.`,
  },
}
